<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <LangVersion>preview</LangVersion>
	  <Nullable>enable</Nullable>
	  <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinFormsPowerTools.StandardBaseTypes\WinFormsPowerTools.StandardBaseTypes.csproj" />
  </ItemGroup>

</Project>
