using Windows.Win32.Graphics.DirectWrite;

namespace System.Windows.Forms.Direct2D
{
    public interface IDirectWriteTextFormat
    {
        public enum FontWeight
        {
            Normal = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_NORMAL,
            Regular = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_REGULAR,
            Bold = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_BOLD,
            Light = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_LIGHT,
            Medium = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_MEDIUM,
            Heavy = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_HEAVY,
            Black = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_EXTRA_BLACK,
            Thin = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_THIN,
            DemiBold = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_DEMI_BOLD,
            SemiLight = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_SEMI_LIGHT,
            SemiBold = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_SEMI_BOLD,
            ExtraLight = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_EXTRA_LIGHT,
            ExtraBold = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_EXTRA_BOLD,
            ExtraBlack = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_EXTRA_BLACK,
            UltraLight = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_ULTRA_LIGHT,
            UltraBold = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_ULTRA_BOLD,
            UltraBlack = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_ULTRA_BLACK
        }

        public enum FontStyle
        {
            Normal = DWRITE_FONT_STYLE.DWRITE_FONT_STYLE_NORMAL,
            Oblique = DWRITE_FONT_STYLE.DWRITE_FONT_STYLE_OBLIQUE,
            Italic = DWRITE_FONT_STYLE.DWRITE_FONT_STYLE_ITALIC
        }

        public enum FontStretch
        {
            Normal = DWRITE_FONT_STRETCH.DWRITE_FONT_STRETCH_NORMAL,
            Condensed = DWRITE_FONT_STRETCH.DWRITE_FONT_STRETCH_CONDENSED,
            Expanded = DWRITE_FONT_STRETCH.DWRITE_FONT_STRETCH_EXPANDED,
            Medium = DWRITE_FONT_STRETCH.DWRITE_FONT_STRETCH_MEDIUM,
            Undefined = DWRITE_FONT_STRETCH.DWRITE_FONT_STRETCH_UNDEFINED,
            ExtraCondensed = DWRITE_FONT_STRETCH.DWRITE_FONT_STRETCH_EXTRA_CONDENSED,
            ExtraExpanded = DWRITE_FONT_STRETCH.DWRITE_FONT_STRETCH_EXTRA_EXPANDED,
            SemiCondensed = DWRITE_FONT_STRETCH.DWRITE_FONT_STRETCH_SEMI_CONDENSED,
            SemiExpanded = DWRITE_FONT_STRETCH.DWRITE_FONT_STRETCH_SEMI_EXPANDED,
            UltraCondensed = DWRITE_FONT_STRETCH.DWRITE_FONT_STRETCH_ULTRA_CONDENSED,
            UltraExpanded = DWRITE_FONT_STRETCH.DWRITE_FONT_STRETCH_ULTRA_EXPANDED
        }

        public enum TextAlignment
        {
            Leading = DWRITE_TEXT_ALIGNMENT.DWRITE_TEXT_ALIGNMENT_LEADING,
            Trailing = DWRITE_TEXT_ALIGNMENT.DWRITE_TEXT_ALIGNMENT_TRAILING,
            Center = DWRITE_TEXT_ALIGNMENT.DWRITE_TEXT_ALIGNMENT_CENTER,
            Justified = DWRITE_TEXT_ALIGNMENT.DWRITE_TEXT_ALIGNMENT_JUSTIFIED
        }

        public enum ParagraphAlignment
        {
            Near = DWRITE_PARAGRAPH_ALIGNMENT.DWRITE_PARAGRAPH_ALIGNMENT_NEAR,
            Far = DWRITE_PARAGRAPH_ALIGNMENT.DWRITE_PARAGRAPH_ALIGNMENT_FAR,
            Center = DWRITE_PARAGRAPH_ALIGNMENT.DWRITE_PARAGRAPH_ALIGNMENT_CENTER,
        }

        public enum TrimmingGranularity
        {
            None = DWRITE_TRIMMING_GRANULARITY.DWRITE_TRIMMING_GRANULARITY_NONE,
            Character = DWRITE_TRIMMING_GRANULARITY.DWRITE_TRIMMING_GRANULARITY_CHARACTER,
            Word = DWRITE_TRIMMING_GRANULARITY.DWRITE_TRIMMING_GRANULARITY_WORD
        }

        public enum BreakConditions
        {
            Neutral = DWRITE_BREAK_CONDITION.DWRITE_BREAK_CONDITION_NEUTRAL,
            MayNotBreak = DWRITE_BREAK_CONDITION.DWRITE_BREAK_CONDITION_MAY_NOT_BREAK,
            CanBreak = DWRITE_BREAK_CONDITION.DWRITE_BREAK_CONDITION_CAN_BREAK,
            MustBreak = DWRITE_BREAK_CONDITION.DWRITE_BREAK_CONDITION_MUST_BREAK
        }

        public enum LineSpacingMethod
        {
            Default = DWRITE_LINE_SPACING_METHOD.DWRITE_LINE_SPACING_METHOD_DEFAULT,
            Proportional = DWRITE_LINE_SPACING_METHOD.DWRITE_LINE_SPACING_METHOD_PROPORTIONAL,
            Uniform = DWRITE_LINE_SPACING_METHOD.DWRITE_LINE_SPACING_METHOD_UNIFORM
        }

        public enum WordWrapping
        {
            NoWrap = DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_NO_WRAP,
            Wrap = DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_WRAP,
            Character = DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_CHARACTER,
            WholeWord = DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_WHOLE_WORD,
            EmergencyBreak = DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_EMERGENCY_BREAK
        }
    }
}
